apiVersion: v1
kind: Pod
metadata:
  name: dustdevil-test
  labels:
    app: dustdevil-test
spec:
  restartPolicy: Never
  containers:
  - name: dustdevil-test
    image: plaidcloud/dustdevil:dev
    imagePullPolicy: Never
    ports:
    - name: http
      hostPort: 80
      containerPort: 8000
  imagePullSecrets:
  - name: dockerhub-key
