apiVersion: v1
kind: Service
metadata:
  name: dustdevil-test
  labels:
    app: dustdevil-test  
spec:
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    plaid: dustdevil-test